blank_issues_enabled: false
contact_links:
  - name: Perguntas & Discussões da Comunidade
    url: https://github.com/Muriel-Gasparini/linkegringo/discussions
    about: Tire dúvidas, compartilhe estratégias de perfil ou discuta o projeto com a comunidade.
