import { describe, expect, it, vi } from 'vitest';
import { createAiProvider, getAvailableProviders } from './registry.js';
import { cleanBase64, extractJsonFromResponse } from './providers/gemini.js';

describe('AI Registry', () => {
  it('returns available providers with gemini and demo', () => {
    const providers = getAvailableProviders();
    expect(providers.length).toBeGreaterThanOrEqual(2);
    expect(providers.some((p) => p.id === 'gemini')).toBe(true);
    expect(providers.some((p) => p.id === 'demo')).toBe(true);
  });

  it('instantiates DemoAiProvider without apiKey', async () => {
    const provider = createAiProvider('demo');
    expect(provider.id).toBe('demo');
    const ok = await provider.testConnection();
    expect(ok).toBe(true);
  });

  it('throws error when instantiating GeminiAiProvider without apiKey', () => {
    expect(() => createAiProvider('gemini', { apiKey: '' })).toThrow(
      'Chave de API do Gemini não informada.',
    );
  });

  it('instantiates GeminiAiProvider with apiKey', () => {
    const provider = createAiProvider('gemini', { apiKey: 'dummy-key-for-test' });
    expect(provider.id).toBe('gemini');
  });

  it('throws for unknown provider', () => {
    expect(() => createAiProvider('non-existent')).toThrow('Provedor de IA desconhecido');
  });
});

describe('Helper Utilities', () => {
  it('cleans base64 data URLs correctly', () => {
    expect(cleanBase64('data:application/pdf;base64,JVBERi0xLjQK')).toBe('JVBERi0xLjQK');
    expect(cleanBase64('JVBERi0xLjQK')).toBe('JVBERi0xLjQK');
    expect(cleanBase64('data:application/pdf;base64, JVBER\n i0xLjQK ')).toBe('JVBERi0xLjQK');
  });

  it('extracts JSON cleanly from markdown code blocks', () => {
    const raw = '```json\n{"score": 95, "title": "Senior"}\n```';
    const parsed = extractJsonFromResponse<{ score: number; title: string }>(raw);
    expect(parsed.score).toBe(95);
    expect(parsed.title).toBe('Senior');
  });

  it('extracts JSON surrounded by preamble text', () => {
    const raw = 'Here is the analysis:\n{"ok": true}\nHope this helps!';
    const parsed = extractJsonFromResponse<{ ok: boolean }>(raw);
    expect(parsed.ok).toBe(true);
  });

  it('extracts JSON from code block even when followed by trailing notes containing braces', () => {
    const raw =
      'Here is the result:\n```json\n{\n  "role": "Architect",\n  "status": "ready"\n}\n```\nExtra note: { do not parse this }';
    const parsed = extractJsonFromResponse<{ role: string; status: string }>(raw);
    expect(parsed.role).toBe('Architect');
    expect(parsed.status).toBe('ready');
  });

  it('handles trailing commas in JSON generated by LLMs', () => {
    const raw = '{\n  "skills": ["Java", "Kafka",],\n  "count": 2,\n}';
    const parsed = extractJsonFromResponse<{ skills: string[]; count: number }>(raw);
    expect(parsed.skills).toEqual(['Java', 'Kafka']);
    expect(parsed.count).toBe(2);
  });
});

describe('Prompts & Deterministic Rubric', () => {
  it('PARSE_AND_DIAGNOSE_SYSTEM_PROMPT includes 5-pillar objective rubric and 90-94 recruiter triage recognition', async () => {
    const { PARSE_AND_DIAGNOSE_SYSTEM_PROMPT } = await import('./prompts.js');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('Objective Scoring Rubric (5 Pillars - Deterministic Evaluation 0-100)');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('Framework XYZ');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('RECOGNITION OF ALREADY OPTIMIZED PROFILES (90 to 94 points - APPROVED FOR US TRIAGE)');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('RECRUITER TRIAGE INQUIRY HEURISTICS (PONTOS DE ATENÇÃO NA TRIAGEM)');
  });

  it('PARSE_AND_DIAGNOSE_SYSTEM_PROMPT strictly prohibits false benchmarks and invented praise', async () => {
    const { PARSE_AND_DIAGNOSE_SYSTEM_PROMPT } = await import('./prompts.js');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('STRICT PROHIBITION OF FALSE BENCHMARKS & FABRICATED PRAISE');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('um dos melhores resumos avaliados');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('top X%');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('melhor que a média');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('100% factual, strictly technical');
  });

  it('PARSE_AND_DIAGNOSE_SYSTEM_PROMPT codifies exhaustive US recruiter red flags catalog and clean section rules', async () => {
    const { PARSE_AND_DIAGNOSE_SYSTEM_PROMPT, buildParseAndDiagnosePrompt } = await import('./prompts.js');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('EXHAUSTIVE CATALOG OF US TECH RECRUITER RED FLAGS');
    
    // Headline
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('Headline Red Flags:');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('Open to work');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('Passionate');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('Ninja');

    // About / Summary
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('About / Summary Red Flags:');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('opening technical hook');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('generic soft skills');

    // Experiences
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('Experiences Red Flags:');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('responsável por');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('STAR framework');

    // Skills & Education
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('Skills & Education Red Flags:');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('Skill salad');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('basic commodity utility tools');

    // Overall Career Coherence
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('Overall Career Coherence & Trajectory Red Flags');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('job hopping');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('Inflated job titles');

    // Rules for sections without red flags
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('RULES FOR SECTIONS AND ISSUES:');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('Sections with zero red flags and zero triage points');

    // buildParseAndDiagnosePrompt critique audit rules
    const prompt = buildParseAndDiagnosePrompt();
    expect(prompt).toContain('CRITIQUE AUDIT RULES:');
    expect(prompt).toContain('US Tech Recruiter Red Flags catalog');
  });

  it('scrubFalseBenchmarks and sanitizeReviewBenchmarks eliminate fabricated cohort claims and enforce severity "low" for clean sections', async () => {
    const { scrubFalseBenchmarks, sanitizeReviewBenchmarks } = await import('./providers/gemini.js');
    
    // Test individual string scrubbing
    expect(scrubFalseBenchmarks('Este é um dos melhores resumos avaliados, com ótima stack.')).not.toContain('um dos melhores resumos avaliados');
    expect(scrubFalseBenchmarks('Candidato no top 5% da base de dados.')).not.toContain('top 5%');
    expect(scrubFalseBenchmarks('Perfil muito melhor que a média dos candidatos.')).not.toContain('melhor que a média');
    expect(scrubFalseBenchmarks('Este é um dos melhores perfis já vistos.')).not.toContain('melhores perfis já vistos');
    expect(scrubFalseBenchmarks('Resumo exemplar entre os candidatos analisados.')).not.toContain('resumo exemplar entre os candidatos analisados');

    // Test full review sanitization
    const fakeReview = {
      targetMarket: 'United States',
      language: 'pt',
      overallScore: 92,
      scores: {
        searchRelevance: 95,
        humanVoice: 95,
        credibility: 90,
        positioningClarity: 90,
        evidenceCoverage: 90,
      },
      executiveSummary: 'Perfil exemplar no top 1% dos candidatos avaliados.',
      profileDirection: {
        positioning: 'Staff Distributed Systems Engineer',
        primaryRole: 'Staff Backend Engineer',
        alternativeRoles: ['Principal Engineer'],
        rationale: 'Forte background em sistemas de alta escala.',
      },
      critique: [
        {
          section: 'Headline',
          assessment: 'Um dos melhores resumos avaliados na área de backend.',
          strengths: ['Entre os melhores da base em clareza'],
          // Rogue issue that should be stripped by PDF artifact filter, leaving empty issues
          issues: ['Falta quebra de parágrafo no resumo por artefato do PDF'],
          severity: 'high' as const,
        },
        {
          section: 'Experiences',
          assessment: 'Experiências sólidas com métricas XYZ.',
          strengths: ['Resultados quantificados em latência e RPS'],
          issues: [],
          severity: 'medium' as const, // Should be normalized to 'low' because issues is []
        },
      ],
      triageBottlenecks: [],
    };

    const sanitized = sanitizeReviewBenchmarks(fakeReview);
    expect(sanitized.executiveSummary).not.toContain('top 1%');
    expect(sanitized.critique[0].assessment).not.toContain('um dos melhores resumos avaliados');
    expect(sanitized.critique[0].strengths[0]).not.toContain('entre os melhores da base');
    // PDF artifact was stripped, resulting in 0 issues
    expect(sanitized.critique[0].issues).toEqual([]);
    // When issues is empty, severity must be normalized to 'low'
    expect(sanitized.critique[0].severity).toBe('low');
    // Second section had empty issues, so severity should be normalized to 'low'
    expect(sanitized.critique[1].severity).toBe('low');
  });

  it('PARSE_AND_DIAGNOSE_SYSTEM_PROMPT enforces strict 100% rule, self-taught credibility, and PDF Top Skills awareness', async () => {
    const { PARSE_AND_DIAGNOSE_SYSTEM_PROMPT, buildParseAndDiagnosePrompt } = await import('./prompts.js');
    
    // PDF Top Skills limitation
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('NOTE ON LINKEDIN PDF SKILLS LIMITATION');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('Save to PDF');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('expandir a lista de competências formais do LinkedIn');

    // Calibrated scoring & zero phantom deductions
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('ZERO PHANTOM DEDUCTIONS');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('REALISTIC CALIBRATION');

    // Self-taught senior engineers merit
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('SENIOR ENGINEERS WITHOUT FORMAL DEGREES (SELF-TAUGHT)');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('basta documentar formações acadêmicas ou cursos formais');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('self-taught');

    // Prompt builder includes the context
    const builtPrompt = buildParseAndDiagnosePrompt();
    expect(builtPrompt).toContain('CONTEXT ON THE DATA SOURCE & LINKEDIN FORMATTING (INCLUDING SKILLS EXPORT)');
    expect(builtPrompt).toContain('ZERO PHANTOM DEDUCTIONS');
  });

  it('sanitizeReviewBenchmarks preserves realistic calibrated scores and removes academic & skills expansion demands', async () => {
    const { sanitizeReviewBenchmarks } = await import('./providers/gemini.js');

    const reviewWithFlawlessExplanations = {
      targetMarket: 'United States',
      language: 'en',
      overallScore: 94,
      scores: {
        searchRelevance: 95,
        humanVoice: 94,
        credibility: 92,
        positioningClarity: 94,
        evidenceCoverage: 95,
      },
      scoreExplanations: {
        searchRelevance:
          'O perfil indexa perfeitamente os termos técnicos centrais (Node.js, NestJS, TypeScript, PostgreSQL, React, Docker, AWS). Para atingir 100%, pode expandir a lista de competências formais do LinkedIn para cobrir todas as tecnologias operacionais citadas no texto.',
        humanVoice:
          'A comunicação é natural em inglês americano idiomático, com tom técnico direto, autoria clara e sem clichês corporativos. O texto transmite autoridade técnica imediata em engenharia de software.',
        credibility:
          'Trajetória profissional sólida com evolução clara de Frontend para Senior Full Stack, detalhando decisões de arquitetura e mitigação de gargalos reais em produção. Para atingir 100%, basta documentar formações acadêmicas ou cursos formais na seção correspondente.',
        positioningClarity:
          'Posicionamento nítido como Senior Full Stack Engineer com profundidade em backend Node.js/NestJS e capacidade autônoma de entrega em React. O escopo técnico e a senioridade estão perfeitamente alinhados entre headline, resumo e histórico.',
        evidenceCoverage: 'Métricas quantificadas de latência e throughput em todas as posições.',
      },
      executiveSummary: 'Perfil sênior com tração técnica internacional.',
      profileDirection: {
        positioning: 'Senior Full Stack Engineer',
        primaryRole: 'Senior Full Stack Engineer',
        alternativeRoles: ['Senior Backend Engineer'],
        rationale: 'Forte background em sistemas distribuídos.',
      },
      critique: [],
      triageBottlenecks: [],
    };

    const result = sanitizeReviewBenchmarks(reviewWithFlawlessExplanations);

    // Authentic scores should be preserved without artificial 100% overrides
    expect(result.scores.searchRelevance).toBe(95);
    expect(result.scores.humanVoice).toBe(94);
    expect(result.scores.credibility).toBe(92);
    expect(result.scores.positioningClarity).toBe(94);
    expect(result.scores.evidenceCoverage).toBe(95);
    expect(result.overallScore).toBe(94);

    // Explanations should not contain academic or PDF skills expansion demands
    expect(result.scoreExplanations?.credibility).not.toContain('basta documentar formações acadêmicas');
    expect(result.scoreExplanations?.searchRelevance).not.toContain('expandir a lista de competências formais');
  });

  it('REWRITE_PROFILE_SYSTEM_PROMPT prohibits invented product niches and enforces role fidelity and headline formula', async () => {
    const { REWRITE_PROFILE_SYSTEM_PROMPT } = await import('./prompts.js');
    expect(REWRITE_PROFILE_SYSTEM_PROMPT).toContain('STRICT PROHIBITION OF INVENTED PRODUCT NICHES');
    expect(REWRITE_PROFILE_SYSTEM_PROMPT).toContain('CRM Platforms');
    expect(REWRITE_PROFILE_SYSTEM_PROMPT).toContain('FIDELITY TO CANDIDATE\'S ROLE');
    expect(REWRITE_PROFILE_SYSTEM_PROMPT).toContain('HIGH-CONVERSION RECRUITER HEADLINE FORMULA');
    expect(REWRITE_PROFILE_SYSTEM_PROMPT).toContain('Senior Full Stack Engineer');
  });

  it('INTERVIEW_PROGRESS_SYSTEM_PROMPT enforces maximum 2 interview rounds', async () => {
    const { INTERVIEW_PROGRESS_SYSTEM_PROMPT } = await import('./prompts.js');
    expect(INTERVIEW_PROGRESS_SYSTEM_PROMPT).toContain('Maximum 2 interview rounds');
    expect(INTERVIEW_PROGRESS_SYSTEM_PROMPT).toContain('readyForGeneration: true');
  });

  it('buildInterviewProgressPrompt includes round number and final round constraint when round >= 2', async () => {
    const { buildInterviewProgressPrompt } = await import('./prompts.js');
    const { MOCK_PROFILE } = await import('./providers/mock.js');
    const objective = {
      targetMarket: 'United States',
      primaryRole: 'Senior Full Stack Engineer',
      seniority: 'senior',
      workPreference: 'remote' as const,
      excludedTechnologies: [],
    };
    const plan = { questions: [] };
    const answers: any[] = [];
    const facts: any[] = [];

    const round1Prompt = buildInterviewProgressPrompt(MOCK_PROFILE, objective, plan, answers, facts, 1);
    expect(round1Prompt).toContain('Interview Round: 1 of 2');
    expect(round1Prompt).not.toContain('FINAL ROUND CONSTRAINT');

    const round2Prompt = buildInterviewProgressPrompt(MOCK_PROFILE, objective, plan, answers, facts, 2);
    expect(round2Prompt).toContain('Interview Round: 2 of 2');
    expect(round2Prompt).toContain('FINAL ROUND CONSTRAINT: This is round 2 of 2. You MUST set readyForGeneration: true and return questions: [] under all circumstances.');
  });

  it('buildInterviewPrompt extracts recruiter triage inquiry points and injects them into the interview prompt', async () => {
    const { buildInterviewPrompt } = await import('./prompts.js');
    const { MOCK_PROFILE, MOCK_REVIEW } = await import('./providers/mock.js');

    const reviewWithInquiry = {
      ...MOCK_REVIEW,
      overallScore: 92,
      critique: [
        {
          section: 'Headline',
          assessment: 'Headline técnica clara.',
          strengths: ['Stack moderna'],
          issues: ['Ponto de atenção na triagem: Headline com 6 tecnologias competindo por atenção.'],
          severity: 'low' as const,
        },
        {
          section: 'Experiences',
          assessment: 'Experiências sólidas.',
          strengths: ['Resultados mensuráveis'],
          issues: ['Ponto de atenção na triagem: Transição recente de 8 meses sem narrativa explícita de conclusão de projeto.'],
          severity: 'low' as const,
        },
      ],
    };

    const prompt = buildInterviewPrompt(
      MOCK_PROFILE,
      {
        targetMarket: 'United States',
        primaryRole: 'Senior Full Stack Engineer',
        seniority: 'senior',
        workPreference: 'remote',
        excludedTechnologies: [],
      },
      'September 2026',
      reviewWithInquiry,
    );

    expect(prompt).toContain('RECRUITER TRIAGE INQUIRY POINTS IDENTIFIED IN DIAGNOSTIC:');
    expect(prompt).toContain('Headline com 6 tecnologias competindo por atenção.');
    expect(prompt).toContain('Transição recente de 8 meses');
    expect(prompt).toContain('Prioritize formulating questions that help the candidate resolve these points');
  });

  it('MockAiProvider respects candidate primaryRole in rewritten headline', async () => {
    const { createAiProvider } = await import('./registry.js');
    const { MOCK_PROFILE } = await import('./providers/mock.js');
    const provider = createAiProvider('demo');

    const analysis = await provider.generateRewrittenProfile({
      profile: MOCK_PROFILE,
      objective: {
        targetMarket: 'United States',
        primaryRole: 'Senior Full Stack Engineer',
        seniority: 'senior',
        workPreference: 'remote',
        excludedTechnologies: [],
      },
      confirmedFacts: [],
    });

    expect(analysis.rewritten.headline).toContain('Senior Full Stack Engineer');
    expect(analysis.rewritten.headline).not.toContain('Senior Backend Engineer');
  });

  it('enforces strict prohibition of emojis in prompts and scrubEmojis scrubber', async () => {
    const {
      PARSE_AND_DIAGNOSE_SYSTEM_PROMPT,
      INTERVIEW_SYSTEM_PROMPT,
      INTERVIEW_PROGRESS_SYSTEM_PROMPT,
      REWRITE_PROFILE_SYSTEM_PROMPT,
    } = await import('./prompts.js');
    const { scrubEmojis } = await import('./providers/gemini.js');

    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('STRICT PROHIBITION OF EMOJIS');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('ZERO emojis');
    expect(INTERVIEW_SYSTEM_PROMPT).toContain('STRICT PROHIBITION OF EMOJIS');
    expect(INTERVIEW_PROGRESS_SYSTEM_PROMPT).toContain('STRICT PROHIBITION OF EMOJIS');
    expect(REWRITE_PROFILE_SYSTEM_PROMPT).toContain('STRICT PROHIBITION OF EMOJIS');

    // scrubEmojis utility: ensures zero emojis, collapses double spaces, and preserves correct punctuation spacing
    expect(scrubEmojis('🎉 Perfil no padrão internacional 💡!')).toBe('Perfil no padrão internacional!');
    expect(scrubEmojis('⚡ High-performance ✨ distributed system 🚀')).toBe('High-performance distributed system');
    expect(scrubEmojis('⚙️ Resiliência em produção 🛡️')).toBe('Resiliência em produção');

    // deepScrubEmojis recursively scrubs across nested objects and arrays
    const { deepScrubEmojis } = await import('./providers/gemini.js');
    const nestedData = {
      headline: 'Senior Backend Engineer 🚀',
      bullets: ['Reduced p99 latency ⚡', 'Architected Kafka pipeline ✨'],
      meta: { note: 'Approved 🎉' },
    };
    const cleaned = deepScrubEmojis(nestedData);
    expect(cleaned.headline).toBe('Senior Backend Engineer');
    expect(cleaned.bullets).toEqual(['Reduced p99 latency', 'Architected Kafka pipeline']);
    expect(cleaned.meta.note).toBe('Approved');
  });

  it('buildParseAndDiagnosePrompt injects targetRole and requires scoreExplanations', async () => {
    const { buildParseAndDiagnosePrompt } = await import('./prompts.js');
    const prompt = buildParseAndDiagnosePrompt('Sample PDF text', 'October 2026', 'Staff Platform Engineer');

    expect(prompt).toContain('TARGET ROLE IN THE US:');
    expect(prompt).toContain('Staff Platform Engineer');
    expect(prompt).toContain('scoreExplanations');
    expect(prompt).toContain('SCORE EXPLANATIONS REQUIREMENT');
  });

  it('buildInterviewPrompt activates Elite Polish Mode when score >= 92', async () => {
    const { buildInterviewPrompt } = await import('./prompts.js');
    const { MOCK_PROFILE, MOCK_REVIEW } = await import('./providers/mock.js');

    const regularPrompt = buildInterviewPrompt(MOCK_PROFILE, {
      targetMarket: 'United States',
      primaryRole: 'Senior Backend Engineer',
      seniority: 'senior',
      workPreference: 'remote',
      excludedTechnologies: [],
    }, 'October 2026', { ...MOCK_REVIEW, overallScore: 78 });
    expect(regularPrompt).not.toContain('ELITE POLISH MODE');

    const polishPrompt = buildInterviewPrompt(MOCK_PROFILE, {
      targetMarket: 'United States',
      primaryRole: 'Senior Backend Engineer',
      seniority: 'senior',
      workPreference: 'remote',
      excludedTechnologies: [],
    }, 'October 2026', { ...MOCK_REVIEW, overallScore: 94 });
    expect(polishPrompt).toContain('ELITE POLISH MODE (Modo Lapidação)');
    expect(polishPrompt).toContain('94/100');
  });

  it('DemoAiProvider calibrates targetRole in parseAndDiagnose and activates Elite Polish questions', async () => {
    const { createAiProvider } = await import('./registry.js');
    const { MOCK_PROFILE, MOCK_REVIEW } = await import('./providers/mock.js');
    const provider = createAiProvider('demo');

    const result = await provider.parseAndDiagnose({ targetRole: 'Lead Cloud Architect' });
    expect(result.review.profileDirection.primaryRole).toBe('Lead Cloud Architect');
    expect(result.review.scoreExplanations?.searchRelevance).toBeDefined();

    const polishPlan = await provider.generateInterview({
      profile: MOCK_PROFILE,
      objective: {
        targetMarket: 'United States',
        primaryRole: 'Lead Cloud Architect',
        seniority: 'senior',
        workPreference: 'remote',
        excludedTechnologies: [],
      },
      review: { ...MOCK_REVIEW, overallScore: 95 },
    });

    expect(polishPlan.questions.some((q) => q.id === 'polish-p99-latency')).toBe(true);
    expect(polishPlan.questions.some((q) => q.reason.includes('Critério dos recrutadores dos EUA'))).toBe(true);
  });
});

describe('fetchGeminiModels', () => {
  it('throws error when apiKey is empty', async () => {
    const { fetchGeminiModels } = await import('./registry.js');
    await expect(fetchGeminiModels('')).rejects.toThrow('Chave de API do Gemini não informada.');
    await expect(fetchGeminiModels('   ')).rejects.toThrow('Chave de API do Gemini não informada.');
  });

  it('throws error with details when API responds with error status', async () => {
    const { fetchGeminiModels } = await import('./registry.js');
    const originalFetch = globalThis.fetch;
    try {
      globalThis.fetch = vi.fn().mockResolvedValue({
        ok: false,
        status: 400,
        statusText: 'Bad Request',
        json: async () => ({
          error: { message: 'API key not valid. Please pass a valid API key.' },
        }),
        text: async () => '',
      } as any);

      await expect(fetchGeminiModels('invalid-key')).rejects.toThrow(
        'Falha ao buscar modelos do Google Gemini (400): API key not valid.',
      );
    } finally {
      globalThis.fetch = originalFetch;
    }
  });

  it('filters non-generateContent and non-gemini models, maps badges and sorts properly', async () => {
    const { fetchGeminiModels } = await import('./registry.js');
    const originalFetch = globalThis.fetch;
    try {
      const mockApiResponse = {
        models: [
          {
            name: 'models/text-embedding-004',
            displayName: 'Text Embedding 004',
            description: 'Embedding model',
            supportedGenerationMethods: ['embedContent'],
          },
          {
            name: 'models/imagen-3.0-generate-002',
            displayName: 'Imagen 3',
            description: 'Image generation',
            supportedGenerationMethods: ['generateContent'],
          },
          {
            name: 'models/gemini-1.5-flash',
            displayName: 'Gemini 1.5 Flash',
            description: 'Fast and versatile model',
            supportedGenerationMethods: ['generateContent', 'countTokens'],
            inputTokenLimit: 1048576,
            outputTokenLimit: 8192,
          },
          {
            name: 'models/gemini-2.0-flash',
            displayName: 'Gemini 2.0 Flash',
            description: 'Next generation multimodal',
            supportedGenerationMethods: ['generateContent'],
            inputTokenLimit: 1048576,
            outputTokenLimit: 8192,
          },
          {
            name: 'models/gemini-2.5-flash',
            displayName: 'Gemini 2.5 Flash Preview',
            description: 'Advanced reasoning preview',
            supportedGenerationMethods: ['generateContent'],
            inputTokenLimit: 1048576,
            outputTokenLimit: 8192,
          },
          {
            name: 'models/gemini-3.5-flash',
            displayName: 'Gemini 3.5 Flash',
            description: 'Recommended fast model',
            supportedGenerationMethods: ['generateContent'],
            inputTokenLimit: 1048576,
            outputTokenLimit: 8192,
          },
          {
            name: 'models/gemini-3.6-flash',
            displayName: 'Gemini 3.6 Flash',
            description: 'Latest recommended model',
            supportedGenerationMethods: ['generateContent'],
            inputTokenLimit: 1048576,
            outputTokenLimit: 8192,
          },
          {
            name: 'models/gemini-3.7-flash',
            displayName: 'Gemini 3.7 Flash',
            description: 'High performance model',
            supportedGenerationMethods: ['generateContent'],
            inputTokenLimit: 1048576,
            outputTokenLimit: 8192,
          },
          {
            name: 'models/gemini-3.8-flash',
            displayName: 'Gemini 3.8 Flash',
            description: 'Advanced model',
            supportedGenerationMethods: ['generateContent'],
            inputTokenLimit: 1048576,
            outputTokenLimit: 8192,
          },
        ],
      };

      globalThis.fetch = vi.fn().mockResolvedValue({
        ok: true,
        status: 200,
        json: async () => mockApiResponse,
      } as any);

      const models = await fetchGeminiModels('valid-test-key');

      // Only gemini 3.5-3.8 flash models with generateContent should remain
      expect(models.length).toBe(4);
      expect(models.some((m) => m.id === 'text-embedding-004')).toBe(false);
      expect(models.some((m) => m.id === 'imagen-3.0-generate-002')).toBe(false);
      expect(models.some((m) => m.id === 'gemini-1.5-flash')).toBe(false);
      expect(models.some((m) => m.id === 'gemini-2.0-flash')).toBe(false);
      expect(models.some((m) => m.id === 'gemini-2.5-flash')).toBe(false);

      // Verify IDs have stripped prefix and modern sorting (3.6 > 3.5 > 3.7 > 3.8)
      expect(models.map((m) => m.id)).toEqual([
        'gemini-3.6-flash',
        'gemini-3.5-flash',
        'gemini-3.7-flash',
        'gemini-3.8-flash',
      ]);

      // Check badges
      const flash35 = models.find((m) => m.id === 'gemini-3.5-flash');
      expect(flash35?.badge).toBe('Recomendado');

      const flash36 = models.find((m) => m.id === 'gemini-3.6-flash');
      expect(flash36?.badge).toBe('Recomendado');

      const flash37 = models.find((m) => m.id === 'gemini-3.7-flash');
      expect(flash37?.badge).toBe('Alta Performance');

      const flash38 = models.find((m) => m.id === 'gemini-3.8-flash');
      expect(flash38?.badge).toBe('Alta Performance');
      expect(flash38?.inputTokenLimit).toBe(1048576);
    } finally {
      globalThis.fetch = originalFetch;
    }
  });

  it('returns empty array when API returns no models', async () => {
    const { fetchGeminiModels } = await import('./registry.js');
    const originalFetch = globalThis.fetch;
    try {
      globalThis.fetch = vi.fn().mockResolvedValue({
        ok: true,
        status: 200,
        json: async () => ({ models: [] }),
      } as any);

      const result = await fetchGeminiModels('test-key');
      expect(result).toEqual([]);
    } finally {
      globalThis.fetch = originalFetch;
    }
  });

  it('handles paginated responses and deduplicates models', async () => {
    const { fetchGeminiModels } = await import('./registry.js');
    const originalFetch = globalThis.fetch;
    try {
      let callCount = 0;
      globalThis.fetch = vi.fn().mockImplementation(async () => {
        callCount++;
        if (callCount === 1) {
          return {
            ok: true,
            status: 200,
            json: async () => ({
              models: [
                {
                  name: 'models/gemini-3.5-flash',
                  displayName: 'Gemini 3.5 Flash',
                  supportedGenerationMethods: ['generateContent'],
                },
                {
                  name: 'models/gemini-3.6-flash',
                  displayName: 'Gemini 3.6 Flash',
                  supportedGenerationMethods: ['generateContent'],
                },
              ],
              nextPageToken: 'token-page-2',
            }),
          };
        }
        return {
          ok: true,
          status: 200,
          json: async () => ({
            models: [
              {
                name: 'models/gemini-3.5-flash', // duplicate to test deduplication
                displayName: 'Gemini 3.5 Flash Dup',
                supportedGenerationMethods: ['generateContent'],
              },
              {
                name: 'models/gemini-3.7-flash',
                displayName: 'Gemini 3.7 Flash',
                supportedGenerationMethods: ['generateContent'],
              },
            ],
          }),
        };
      });

      const models = await fetchGeminiModels('valid-key');
      expect(callCount).toBe(2);
      expect(models.length).toBe(3);
      expect(models.map((m) => m.id)).toEqual([
        'gemini-3.6-flash',
        'gemini-3.5-flash',
        'gemini-3.7-flash',
      ]);
    } finally {
      globalThis.fetch = originalFetch;
    }
  });

  it('prioritizes gemini 3.6 flash then 3.5 flash in getModelSortWeight', async () => {
    const { getModelSortWeight } = await import('./registry.js');
    const weight36Flash = getModelSortWeight('gemini-3.6-flash');
    const weight35Flash = getModelSortWeight('gemini-3.5-flash');
    const weight37Flash = getModelSortWeight('gemini-3.7-flash');
    const weight38Flash = getModelSortWeight('gemini-3.8-flash');

    expect(weight36Flash).toBeGreaterThan(weight35Flash);
    expect(weight35Flash).toBeGreaterThan(weight37Flash);
    expect(weight37Flash).toBeGreaterThan(weight38Flash);
  });
});

