import { describe, expect, it } from 'vitest';
import { createAiProvider, getAvailableProviders } from './registry.js';
import { cleanBase64, extractJsonFromResponse } from './providers/gemini.js';

describe('AI Registry', () => {
  it('returns available providers with gemini and demo', () => {
    const providers = getAvailableProviders();
    expect(providers.length).toBeGreaterThanOrEqual(2);
    expect(providers.some((p) => p.id === 'gemini')).toBe(true);
    expect(providers.some((p) => p.id === 'demo')).toBe(true);
  });

  it('instantiates DemoAiProvider without apiKey', async () => {
    const provider = createAiProvider('demo');
    expect(provider.id).toBe('demo');
    const ok = await provider.testConnection();
    expect(ok).toBe(true);
  });

  it('throws error when instantiating GeminiAiProvider without apiKey', () => {
    expect(() => createAiProvider('gemini', { apiKey: '' })).toThrow(
      'Chave de API do Gemini não informada.',
    );
  });

  it('instantiates GeminiAiProvider with apiKey', () => {
    const provider = createAiProvider('gemini', { apiKey: 'dummy-key-for-test' });
    expect(provider.id).toBe('gemini');
  });

  it('throws for unknown provider', () => {
    expect(() => createAiProvider('non-existent')).toThrow('Provedor de IA desconhecido');
  });
});

describe('Helper Utilities', () => {
  it('cleans base64 data URLs correctly', () => {
    expect(cleanBase64('data:application/pdf;base64,JVBERi0xLjQK')).toBe('JVBERi0xLjQK');
    expect(cleanBase64('JVBERi0xLjQK')).toBe('JVBERi0xLjQK');
    expect(cleanBase64('data:application/pdf;base64, JVBER\n i0xLjQK ')).toBe('JVBERi0xLjQK');
  });

  it('extracts JSON cleanly from markdown code blocks', () => {
    const raw = '```json\n{"score": 95, "title": "Senior"}\n```';
    const parsed = extractJsonFromResponse<{ score: number; title: string }>(raw);
    expect(parsed.score).toBe(95);
    expect(parsed.title).toBe('Senior');
  });

  it('extracts JSON surrounded by preamble text', () => {
    const raw = 'Here is the analysis:\n{"ok": true}\nHope this helps!';
    const parsed = extractJsonFromResponse<{ ok: boolean }>(raw);
    expect(parsed.ok).toBe(true);
  });

  it('extracts JSON from code block even when followed by trailing notes containing braces', () => {
    const raw =
      'Here is the result:\n```json\n{\n  "role": "Architect",\n  "status": "ready"\n}\n```\nExtra note: { do not parse this }';
    const parsed = extractJsonFromResponse<{ role: string; status: string }>(raw);
    expect(parsed.role).toBe('Architect');
    expect(parsed.status).toBe('ready');
  });

  it('handles trailing commas in JSON generated by LLMs', () => {
    const raw = '{\n  "skills": ["Java", "Kafka",],\n  "count": 2,\n}';
    const parsed = extractJsonFromResponse<{ skills: string[]; count: number }>(raw);
    expect(parsed.skills).toEqual(['Java', 'Kafka']);
    expect(parsed.count).toBe(2);
  });
});

describe('Prompts & Deterministic Rubric', () => {
  it('PARSE_AND_DIAGNOSE_SYSTEM_PROMPT includes 5-pillar objective rubric and 92-100 recognition', async () => {
    const { PARSE_AND_DIAGNOSE_SYSTEM_PROMPT } = await import('./prompts.js');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('Objective Scoring Rubric (5 Pillars - Deterministic Evaluation 0-100)');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('Framework XYZ');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('RECOGNITION OF ALREADY OPTIMIZED PROFILES (92 to 100 points)');
    expect(PARSE_AND_DIAGNOSE_SYSTEM_PROMPT).toContain('DO NOT invent fictitious problems');
  });

  it('REWRITE_PROFILE_SYSTEM_PROMPT prohibits invented product niches and enforces role fidelity and headline formula', async () => {
    const { REWRITE_PROFILE_SYSTEM_PROMPT } = await import('./prompts.js');
    expect(REWRITE_PROFILE_SYSTEM_PROMPT).toContain('STRICT PROHIBITION OF INVENTED PRODUCT NICHES');
    expect(REWRITE_PROFILE_SYSTEM_PROMPT).toContain('CRM Platforms');
    expect(REWRITE_PROFILE_SYSTEM_PROMPT).toContain('FIDELITY TO CANDIDATE\'S ROLE');
    expect(REWRITE_PROFILE_SYSTEM_PROMPT).toContain('HIGH-CONVERSION RECRUITER HEADLINE FORMULA');
    expect(REWRITE_PROFILE_SYSTEM_PROMPT).toContain('Senior Full Stack Engineer');
  });

  it('INTERVIEW_PROGRESS_SYSTEM_PROMPT enforces maximum 2 interview rounds', async () => {
    const { INTERVIEW_PROGRESS_SYSTEM_PROMPT } = await import('./prompts.js');
    expect(INTERVIEW_PROGRESS_SYSTEM_PROMPT).toContain('Maximum 2 interview rounds');
    expect(INTERVIEW_PROGRESS_SYSTEM_PROMPT).toContain('readyForGeneration: true');
  });

  it('buildInterviewProgressPrompt includes round number and final round constraint when round >= 2', async () => {
    const { buildInterviewProgressPrompt } = await import('./prompts.js');
    const { MOCK_PROFILE } = await import('./providers/mock.js');
    const objective = {
      targetMarket: 'United States',
      primaryRole: 'Senior Full Stack Engineer',
      seniority: 'senior',
      workPreference: 'remote' as const,
      excludedTechnologies: [],
    };
    const plan = { questions: [] };
    const answers: any[] = [];
    const facts: any[] = [];

    const round1Prompt = buildInterviewProgressPrompt(MOCK_PROFILE, objective, plan, answers, facts, 1);
    expect(round1Prompt).toContain('Current Evaluation Round: Round 1 of 2.');
    expect(round1Prompt).not.toContain('THIS IS ROUND 2 (FINAL ROUND)');

    const round2Prompt = buildInterviewProgressPrompt(MOCK_PROFILE, objective, plan, answers, facts, 2);
    expect(round2Prompt).toContain('Current Evaluation Round: Round 2 of 2.');
    expect(round2Prompt).toContain('THIS IS ROUND 2 (FINAL ROUND): You MUST set readyForGeneration: true and questions: []');
  });

  it('MockAiProvider respects candidate primaryRole in rewritten headline', async () => {
    const { createAiProvider } = await import('./registry.js');
    const { MOCK_PROFILE } = await import('./providers/mock.js');
    const provider = createAiProvider('demo');

    const analysis = await provider.generateRewrittenProfile({
      profile: MOCK_PROFILE,
      objective: {
        targetMarket: 'United States',
        primaryRole: 'Senior Full Stack Engineer',
        seniority: 'senior',
        workPreference: 'remote',
        excludedTechnologies: [],
      },
      confirmedFacts: [],
    });

    expect(analysis.rewritten.headline).toContain('Senior Full Stack Engineer');
    expect(analysis.rewritten.headline).not.toContain('Senior Backend Engineer');
  });
});

